<?php

declare(strict_types=1);

/**
 * Random cross-check: replays games generated by the vendored chess.js 1.4.0
 * reference (see backend/tests/helpers/generate-random-games.mjs) through the
 * PHP engine and asserts, after EVERY move:
 *
 *   - identical FEN strings,
 *   - identical sorted lists of legal moves in SAN,
 *   - identical check / checkmate / stalemate / insufficient-material /
 *     threefold / 50-move / game-over flags,
 *   - identical history when replayed a second time via UCI move strings.
 *
 * The generator requires Node and is OPTIONAL in CI: when the JSON data file
 * is missing this script reports a skip (exit 0) instead of failing.
 *
 * Usage:
 *   node backend/tests/helpers/generate-random-games.mjs   # generate data first
 *   php backend/tests/chess-random.php [path/to/games.json]
 *
 * Default data path: /tmp/opencode/chess-random-games.json
 * (override with argv[1] or env CHECKMATE_RANDOM_GAMES).
 *
 * Exit code 0 = all assertions passed (or data missing), 1 = mismatch.
 */

require_once __DIR__ . '/../src/Autoloader.php';
\Checkmate\Autoloader::register();

use Checkmate\Game\Game;

function randomCrossCheckDefaultPath(): string
{
    $env = getenv('CHECKMATE_RANDOM_GAMES');
    return is_string($env) && $env !== '' ? $env : '/tmp/opencode/chess-random-games.json';
}

/**
 * Replay all games and compare against the reference data.
 *
 * @return array{
 *     status: 'ok'|'missing'|'fail',
 *     games: int, plies: int, checks: int,
 *     failures: string[],
 * }
 */
function runRandomCrossCheck(string $file, int $maxFailures = 25): array
{
    if (!is_file($file)) {
        return ['status' => 'missing', 'games' => 0, 'plies' => 0, 'checks' => 0, 'failures' => []];
    }

    $data = json_decode((string) file_get_contents($file), true, 512, JSON_THROW_ON_ERROR);
    $games = $data['games'] ?? null;
    if (!is_array($games) || $games === []) {
        throw new RuntimeException("{$file}: no games in data file");
    }

    $failures = [];
    $checks = 0;
    $plies = 0;
    $failedGames = 0;

    $fail = static function (string $message) use (&$failures, $maxFailures): void {
        if (count($failures) < $maxFailures) {
            $failures[] = $message;
        }
    };

    foreach ($games as $gameIndex => $game) {
        $sans = $game['moves'];
        $ucis = $game['ucis'];
        $fens = $game['fens'];
        $legalSans = $game['legalSans'];
        $flags = $game['flags'];
        $gameFailuresBefore = count($failures);
        $plies += count($sans);

        // ---- pass 1: replay via SAN ------------------------------------
        $php = Game::fromFen($game['startFen']);
        $n = count($sans);
        for ($i = 0; $i <= $n; $i++) {
            $checks += 3;

            $expectedFen = $i === 0 ? $game['startFen'] : $fens[$i - 1];
            if ($php->fen() !== $expectedFen) {
                $fail("game {$game['id']} ply {$i}: fen mismatch, expected {$expectedFen}, got " . $php->fen());
                continue 2;
            }

            $mySans = $php->sanMoves();
            sort($mySans);
            if ($mySans !== $legalSans[$i]) {
                $diff = array_merge(
                    array_diff($legalSans[$i], $mySans),
                    array_diff($mySans, $legalSans[$i]),
                );
                $fail("game {$game['id']} ply {$i}: legal SAN list differs (e.g. " . implode(',', array_slice($diff, 0, 8)) . ')');
                continue 2;
            }

            $myFlags = [
                'check' => $php->isCheck(),
                'checkmate' => $php->isCheckmate(),
                'stalemate' => $php->isStalemate(),
                'insufficient' => $php->isInsufficientMaterial(),
                'threefold' => $php->isThreefoldRepetition(),
                'fifty' => $php->isDrawByFiftyMoves(),
                'gameOver' => $php->isGameOver(),
            ];
            if ($myFlags !== $flags[$i]) {
                $expected = json_encode($flags[$i]);
                $got = json_encode($myFlags);
                $fail("game {$game['id']} ply {$i}: flags differ, expected {$expected}, got {$got}");
                continue 2;
            }

            if ($i < $n) {
                $php = $php->play($sans[$i]);
            }
        }

        if ($php->history() !== $sans) {
            $checks++;
            $fail("game {$game['id']}: generated SAN history differs from reference move list");
        }

        // ---- pass 2: replay via UCI ------------------------------------
        $phpUci = Game::fromFen($game['startFen']);
        for ($i = 0; $i < $n; $i++) {
            $phpUci = $phpUci->play($ucis[$i]);
            $checks++;
            if ($phpUci->fen() !== $fens[$i]) {
                $fail("game {$game['id']} uci ply {$i}: fen mismatch after {$ucis[$i]}, expected {$fens[$i]}, got " . $phpUci->fen());
                break;
            }
        }
        if ($phpUci->historyUci() !== $ucis) {
            $checks++;
            $fail("game {$game['id']}: UCI history differs from reference list");
        }
        if ($phpUci->fen() !== $php->fen()) {
            $checks++;
            $fail("game {$game['id']}: SAN and UCI replays disagree");
        }

        if (count($failures) > $gameFailuresBefore) {
            $failedGames++;
        }
        if (count($failures) >= $maxFailures) {
            $failures[] = '... too many failures, aborting early ...';
            break;
        }
    }

    $gameCount = is_array($games) ? count($games) : 0;
    return [
        'status' => $failures === [] ? 'ok' : 'fail',
        'games' => $gameCount,
        'plies' => $plies,
        'checks' => $checks,
        'failures' => $failures,
        'failedGames' => $failedGames,
    ];
}

// ---------------------------------------------------------------------------
// CLI entry point (only when executed directly, not when included by the suite)
// ---------------------------------------------------------------------------
if (isset($_SERVER['SCRIPT_FILENAME']) && realpath($_SERVER['SCRIPT_FILENAME']) === __FILE__) {
    $path = $argv[1] ?? randomCrossCheckDefaultPath();
    $result = runRandomCrossCheck($path);

    if ($result['status'] === 'missing') {
        echo "Random cross-check: SKIPPED (data file not found: {$path})\n";
        echo "Generate it with: node backend/tests/helpers/generate-random-games.mjs\n";
        exit(0);
    }

    foreach ($result['failures'] as $failure) {
        echo "FAIL {$failure}\n";
    }
    printf(
        "Random cross-check: %s - %d games, %d plies, %d assertions\n",
        $result['status'] === 'ok' ? 'PASS' : 'FAIL',
        $result['games'],
        $result['plies'],
        $result['checks'],
    );
    exit($result['status'] === 'ok' ? 0 : 1);
}
